spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherapp
    username: root
    password:
temperature:
  url: https://api.weather.gov/gridpoints/EWX/156,91/forecast/hourly
  pathToResponse: $.properties.periods[0].temperature